### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by writepavel** [olivergg/scalajs-ionic-starttabs#2]
I want to use [Sourcegraph](https://sourcegraph.com) for scalajs-ionic-starttabs code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/olivergg/scalajs-ionic-starttabs. (It should only take 30 seconds.)

Thank you!

**Comment by olivergg** [comment]
Done.
